# Generated by Django 3.2 on 2022-08-15 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 20, 32, 48, 685789, tzinfo=utc)),
        ),
    ]
