# Generated by Django 3.2 on 2022-08-15 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
           field=models.DateTimeField(default=now),

        ),
    ]
